import { Grid, Title } from '@mantine/core';
import { useSession } from 'next-auth/react';
import Head from 'next/head';
import { useEffect } from 'react';

import { TrackCard } from '../components/TrackCard';
import { greeting } from '../utils/greeting';
import { useAppDispatch, useAppSelector } from '../utils/state/hooks';
import { fetchTracks } from '../utils/state/tracks/tracks.actions';
import { selectTracks } from '../utils/state/tracks/tracks.reducer';

import type { NextPage } from "next";
const Home: NextPage = () => {
  const dispatch = useAppDispatch();
  const { data: session } = useSession();
  const tracks = useAppSelector((state) => selectTracks(state.tracks));

  useEffect(() => {
    if (session) {
      dispatch(fetchTracks(session));
    }
  }, [session?.user?.email]);

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <Title order={2}>Hello! {greeting()}!</Title>

        <Title order={2}>Recently Played</Title>

        <Grid className="max-w-full" gutter="sm" mt={10}>
          {tracks.map((track) => {
            return (
              <Grid.Col key={track.id} sm={4} md={3}>
                <TrackCard track={track} />
              </Grid.Col>
            );
          })}
        </Grid>
      </div>
    </>
  );
};

export default Home;
