import { Grid, Title } from '@mantine/core';
import Head from 'next/head';
import { useEffect } from 'react';

import { TrackCard } from '../components/TrackCard';
import { useAppDispatch, useAppSelector } from '../state/state.models';
import { fetchTracks } from '../state/tracks/tracks.actions';
import { selectAllTracks } from '../state/tracks/tracks.selectors';
import { greeting } from '../utils';

import type { NextPage } from "next";
const Home: NextPage = () => {
  const dispatch = useAppDispatch();
  const tracks = useAppSelector(selectAllTracks);

  useEffect(() => {
    dispatch(fetchTracks());
  }, [dispatch]);

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <Title order={2}>Hello! {greeting()}!</Title>

        <Title order={2}>Recently Played</Title>

        <Grid className="max-w-full" gutter="sm" mt={10}>
          {tracks.map((track) => {
            return (
              <Grid.Col key={track.id} sm={4} md={3}>
                <TrackCard track={track} />
              </Grid.Col>
            );
          })}
        </Grid>
      </div>
    </>
  );
};

export default Home;
